done for norm parse

diff --git a/TODO b/TODO
--- a/TODO
+++ b/TODO
@@ -1,51 +1,101 @@
+export x="ls    -la" : tab
+
+x="a b"
+
+export $x=$x => export (a  b=a  b) => a, b=a, b,
+
+
+export a b=a b
+
+export x="ls -la"
+
+
+'"'"$HOME"'"'
+
+echo ".$HOME..$PWD..."
+
+
+update in env
+
+'"'$HOME'"'
+
+# stil work on exit and exit status , more fixing t9abi in env !
+
+
+~ minishell 𒌐 cat << a
+> '$PWD'
+> a
+'$PWD'
+
 
 ~ minishell 𒌐 cat << 'a'
 Syntax error
 ~ minishell 𒌐 cat << "a"
 Syntax error
 
-problems in Herdoc << 
 
-int	handle_heredoc_fork(t_token *lst, t_exec *node, t_env *env, int fd_out)
-{
-	int	pid;
-	int	statu
-	status = 0;
-	pid = fork();
-	if (pid < 0)
-		return (perror("fork"), close(fd_out), 1);
-	else if (pid == 0)
-	{
-		if (node->fd_in != 0)
-			close(node->fd_in);
-		signal(SIGINT, SIG_DFL);
-		ft_handle_heredoc(lst, env, fd_out);
-	}
-	else
-		waitpid(pid, &status, 0);
-	signal(SIGINT, &handler);
-	rl_replace_line("", 0);
-	if (WIFSIGNALED(status))
-		return (store_exit_status(130, 1), 1);
-	return (0);
-}
-int	handle_heredoc(t_token **lst, t_exec *node, t_env *env)
-{
-	char	*f_adress;
-	int		fd_ou
-	if (!(*lst)->next)
-		return (ambigous_red(), 1);
-	f_adress = ft_malloc(100, ALLOC);
-	f_adress = ft_strj("/tmp/", ft_itoa(((long)&fd_out)));
-	fd_out = open(f_adress, O_TRUNC | O_WRONLY | O_CREAT, 0777);
-	if (handle_heredoc_fork(*lst, node, env, fd_out))
-		return (1);
-	node->fd_in = open(f_adress, O_RDONLY);
-	if (node->fd_in == -1)
-	{
-		perror("minishell");
-		while ((*lst) && (*lst)->type != PIPE)
-			(*lst) = (*lst)->next;
-	}
-	return (0);
-}
+export x="ls <space/tab> -la"
+
+
+~ minishell 𒌐 l"s"">"a
+ls>a: command not found
+
+=================================================================
+==19311==ERROR: LeakSanitizer: detected memory leaks
+
+Direct leak of 22 byte(s) in 2 object(s) allocated from:
+    #0 0x49a26d in malloc (/home/sbaghdad/Desktop/minishell/minishell+0x49a26d)
+    #1 0x7fdfaea63bac in xmalloc (/lib/x86_64-linux-gnu/libreadline.so.8+0x39bac)
+
+SUMMARY: AddressSanitizer: 22 byte(s) leaked in 2 allocation(s).
+
+
+
+~ minishell 𒌐 $OLDPWD
+execve(): Permission denied
+
+
+
+~ shell >$OLDPWD
+execve(): Permission denied
+=================================================================
+==22499==ERROR: AddressSanitizer: attempting double-free on 0x604000000c10 in thread T0:
+
+~ minishell 𒌐 unset PATH
+~ minishell 𒌐 ls
+ls: command not found
+~ minishell 𒌐 cd /bin
+~ bin 𒌐 ls
+ls: command not found
+
+=================================================================
+
+~ minishell 𒌐 chmod 000 e
+~ minishell 𒌐 < Makefile > e > uuuy
+
+
+in syntac err set exit stuts to 2 !!!!!
+
+echo $"?" in minishell
+$?
+in bash
+?
+
+e$ echo "JEEEE" > messi > car > "" >> ls
+in bash => bash: : No such file or directory
+in minishell it's pass
+
+cat | cat | cat | cat | cat | cat
+
+cntr + C
+cntr + C
+cntr + C
+cntr + C
+cntr + C
+cntr + D
+exit status
+
+
+mkdir -p 1/2/3
+cd ..
+double free !!!
